### PR TITLE
Remove comments

### PR DESCRIPTION
**Pull request by pauljeter**
## Description
Remove comments from final bundle and individually import Lodash functions.

## Motivation and Context
Reduce bundle size from 5.93 MB to 698 KB

## How Has This Been Tested?
All unit tests are passing.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by bfbiggs** [comment]
Just changed it to eval source map - do we want the full source map?

**Comment by pauljeter** [comment]
> Just changed it to eval source map - do we want the full source map?

Through research, discovered that this was one of the issues with the bloated bundle size. The UglifyJSPlugin does not play well with the other sourcemaps.

**Comment by bfbiggs** [comment]
So could we overwrite that in prod/lib configs instead of base config? One of the reasons I changed that was to speed up Dev builds

**Comment by pauljeter** [comment]
Good call. I updated the configs.

**Pull request merged**
